#!/bin/bash

export BINUTILSVER=2.36.1
export BINUTILSREV=
export GCCVER=11.5.0
export GCCREV=
export NEWLIBVER=4.1.0
export NEWLIBREV=
export MPCVER=1.2.1
export MPCREV=
export MPFRVER=4.1.0
export MPFRREV=
export GMPVER=6.2.1
export GMPREV=

export ENABLE_DOWNLOAD_CACHE=${ENABLE_DOWNLOAD_CACHE:=1}
export ENABLE_STATIC_BUILD=${ENABLE_STATIC_BUILD:=0}

exec "$@"
